name: mwdb
channels:
  - defaults
dependencies:
  - bzip2==1.0.8
  - ca-certificates==2021.7.5
  - certifi==2021.5.30
  - cytoolz==0.11.0
  - matplotlib==3.4.2
  - numpy-base==1.20.3
  - pillow==8.3.1
  - pip==21.2.4
  - python>=3.9.7
  - python-dateutil==2.8.2
  - scikit-image==0.18.1
  - scipy==1.7.1
  - setuptools==58.0.4
  - pandas
  - pip:
    - joblib==1.0.1
    - numpy==1.21.2
    - scikit-learn==1.0
    - threadpoolctl==3.0.0
    - numpyencoder
    - cvxopt
